c++_class_demo: c++_class_demo.o
	g++ -o c++_class_demo c++_class_demo.o -std=c++2a

c++_class_demo.o: c++_class_demo.cpp
	g++ -c c++_class_demo.cpp -std=c++2a

clean:
	rm c++_class_demo c++_class_demo.o
